# Generated by Django 2.2.5 on 2020-04-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserorder',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='purchaserorder',
            name='creation_date',
        ),
    ]
