# Generated by Django 2.2.5 on 2020-04-11 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PurchaseOrder', '0002_auto_20200411_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserorder',
            name='last_update_by',
        ),
        migrations.RemoveField(
            model_name='purchaserorder',
            name='last_update_date',
        ),
        migrations.RemoveField(
            model_name='purchaserorder',
            name='products',
        ),
        migrations.RemoveField(
            model_name='purchaserorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchaserorder',
            name='Approval',
            field=models.CharField(choices=[('AD', 'Approved'), ('RJ', 'Rejected'), ('HD', 'OnHold')], default='onHold', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserorder',
            name='Approval_comments',
            field=models.CharField(default='at to be reviewed', max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PoItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('tax', models.IntegerField()),
                ('total', models.FloatField()),
                ('product_status', models.BooleanField()),
                ('last_update_date', models.DateTimeField()),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_updated', to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_num', to='PurchaseOrder.PurchaserOrder')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom', to='product.Product')),
            ],
        ),
    ]
