# Generated by Django 2.2.5 on 2020-04-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0003_auto_20200411_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserorder',
            name='Approval',
            field=models.CharField(choices=[('CR', 'Created'), ('AD', 'Approved'), ('RJ', 'Rejected'), ('HD', 'OnHold')], default='Created', max_length=30),
        ),
    ]
