# Generated by Django 2.2.5 on 2020-04-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0004_auto_20200411_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitems',
            name='tax',
        ),
        migrations.AddField(
            model_name='purchaserorder',
            name='tax',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
