# Generated by Django 2.2.5 on 2020-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('SE', 'sale executive'), ('IM', 'inventory Manager'), ('PM', 'Purchase Manager'), ('Sup', 'Supplier')], max_length=30),
        ),
    ]
