# Generated by Django 2.2.5 on 2020-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='prnum',
            field=models.CharField(default='1', max_length=300),
            preserve_default=False,
        ),
    ]
