# Generated by Django 2.2.5 on 2020-04-10 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobnum', models.CharField(max_length=10)),
                ('Adderss', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField()),
                ('creation_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField()),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_created', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_updated', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
